# on:
#   push:
#     branches: "main"

# jobs:
#   build:
#     runs-on: "ubuntu-latest"
#     permissions:
#       contents: "read"
#       id-token: "write"

#     steps:
#       - uses: "actions/checkout@v4"
#       - uses: "oven-sh/setup-bun@v1"

#       - run: "bun run build:function"

#       - id: "auth"
#         uses: "google-github-actions/auth@v1"
#         with:
#           workload_identity_provider: "projects/477772360728/locations/global/workloadIdentityPools/pool/providers/github-actions-oidc"
#           service_account: "conint@organic-folder-403021.iam.gserviceaccount.com"

#       - id: "deploy"
#         uses: "google-github-actions/deploy-cloud-functions@v1"
#         with:
#           name: "splendor"
#           runtime: "nodejs20"
#           region: "europe-west3"
#           source_dir: "./function"
#           entry_point: "index.js"
